version: "3" 
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyR00tMySQLeasyVideoPassword
      MYSQL_DATABASE: easy_video_database
      MYSQL_USER: easy_video_user
      MYSQL_PASSWORD: easyVideoPassword
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: easy_video_user
      PMA_PASSWORD: easyVideoPassword
    ports:
      - "8081:80"
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: easy_video_user
      WORDPRESS_DB_PASSWORD: easyVideoPassword
      WORDPRESS_DB_NAME: easy_video_database
    volumes:
      - "./:/var/www/html/wp-content/plugins/easy-videos"                 # (Volume 1 )Easy Video Extension
      - "../typerocket-v5:/var/www/html/wp-content/plugins/typerocket-v5" # (Volume 2) TypeRocket Extension
                                                                          #Download it from https://typerocket.com/downloads/v5.zip 
                                                                          #and unzip it  for typerocket Framework , You need to extract
                                                                          # it and set his path herer 
      - "../public:/var/www/html"                                         # (Volume 3) Physical path
      #- "path/for/themes:/var/www/html/wp-content/themes"
volumes:
  mysql: {}
